steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/fleet-dev-1/llm-healthcheck/llm-healthcheck-v0.0.8', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/fleet-dev-1/llm-healthcheck/llm-healthcheck-v0.0.8']
images: ['us-docker.pkg.dev/fleet-dev-1/llm-healthcheck/llm-healthcheck-v0.0.8']